# Generated by Django 2.2.9 on 2020-01-24 20:33

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank='(select country)', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PublicService',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('links', models.URLField()),
                ('purpose', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('email_user_support', models.EmailField(blank=True, max_length=254, null=True)),
                ('quotas', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('logo', models.URLField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public_appliances.Location')),
                ('sponsors', models.ManyToManyField(blank=True, to='public_appliances.Sponsor')),
                ('tags', models.ManyToManyField(blank=True, to='public_appliances.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
