# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('info_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30)),
                ('launch_data', models.TextField(blank=True, help_text='Instance user data to parameterize the launch.', max_length=16384, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='baselaunch.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('image_id', models.CharField(max_length=50, verbose_name='Image ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AWSEC2',
            fields=[
                ('infrastructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baselaunch.Infrastructure')),
                ('kind', models.CharField(choices=[('cloud', 'Cloud'), ('container', 'Container'), ('local', 'Local')], default='cloud', editable=False, max_length=10)),
                ('region_name', models.CharField(max_length=100)),
                ('region_endpoint', models.CharField(max_length=255)),
                ('is_secure', models.BooleanField()),
                ('ec2_port', models.IntegerField(blank=True, null=True, verbose_name='EC2 port')),
                ('ec2_conn_path', models.CharField(default='/', max_length=255, verbose_name='EC2 conn path')),
            ],
            options={
                'verbose_name': 'AWS EC2',
                'verbose_name_plural': 'AWS EC2',
            },
            bases=('baselaunch.infrastructure',),
        ),
        migrations.CreateModel(
            name='AWSS3',
            fields=[
                ('infrastructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baselaunch.Infrastructure')),
                ('kind', models.CharField(choices=[('cloud', 'Cloud'), ('container', 'Container'), ('local', 'Local')], default='cloud', editable=False, max_length=10)),
                ('s3_host', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_port', models.IntegerField(blank=True, null=True)),
                ('s3_conn_path', models.CharField(blank=True, default='/', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'AWS S3',
                'verbose_name_plural': 'AWS S3',
            },
            bases=('baselaunch.infrastructure',),
        ),
        migrations.CreateModel(
            name='OpenStack',
            fields=[
                ('infrastructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baselaunch.Infrastructure')),
                ('kind', models.CharField(choices=[('cloud', 'Cloud'), ('container', 'Container'), ('local', 'Local')], default='cloud', editable=False, max_length=10)),
                ('auth_url', models.CharField(max_length=255)),
                ('region_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'OpenStack',
                'verbose_name_plural': 'OpenStack',
            },
            bases=('baselaunch.infrastructure',),
        ),
        migrations.AddField(
            model_name='image',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baselaunch.Infrastructure'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='image_id',
            field=models.ManyToManyField(blank=True, to='baselaunch.Image'),
        ),
    ]
