# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baselaunch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('access_key', models.CharField(max_length=50)),
                ('secret_key', models.CharField(max_length=50)),
                ('cloud', models.ManyToManyField(to='baselaunch.AWS')),
            ],
            options={
                'verbose_name': 'AWS Credentials',
                'verbose_name_plural': 'AWS Credentials',
            },
        ),
        migrations.CreateModel(
            name='OpenStackCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('tenant_name', models.CharField(max_length=50)),
                ('cloud', models.ManyToManyField(to='baselaunch.OpenStack')),
            ],
            options={
                'verbose_name': 'OpenStack Credentials',
                'verbose_name_plural': 'OpenStack Credentials',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='openstackcredentials',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baselaunch.UserProfile'),
        ),
        migrations.AddField(
            model_name='awscredentials',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baselaunch.UserProfile'),
        ),
    ]
