# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0003_application_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdeployment',
            name='celery_task_id',
            field=models.TextField(blank=True, help_text='Celery task id forany background jobs running on this deployment', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdeployment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
