# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0004_deployment_model_celery'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdeployment',
            name='task_result',
            field=models.TextField(blank=True, help_text='Result of celery task', max_length=16384, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdeployment',
            name='celery_task_id',
            field=models.TextField(blank=True, help_text='Celery task id for any background jobs running on this deployment', max_length=64, null=True, unique=True),
        ),
    ]
