# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0006_public_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank='(select country)', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='publicservice',
            name='country',
        ),
        migrations.RemoveField(
            model_name='publicservice',
            name='location',
        ),
    ]
