# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0007_auto_20160625_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicservice',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baselaunch.Location'),
        ),
    ]
