# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0007_app_config_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank='(select country)', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='publicservice',
            name='country',
        ),
        migrations.AlterField(
            model_name='publicservice',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baselaunch.Location'),
        ),
    ]
