# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0008_publicservice_location'),
        ('baselaunch', '0007_app_config_fields'),
    ]

    operations = [
    ]
