# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0008_app_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
    ]
