# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0010_openstack_credential_fixes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdeployment',
            name='instance_type',
        ),
        migrations.RemoveField(
            model_name='applicationdeployment',
            name='keypair_name',
        ),
        migrations.RemoveField(
            model_name='applicationdeployment',
            name='network',
        ),
        migrations.RemoveField(
            model_name='applicationdeployment',
            name='placement_zone',
        ),
        migrations.RemoveField(
            model_name='applicationdeployment',
            name='subnet',
        ),
    ]
