# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 12:41
from __future__ import unicode_literals

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0011_remove_app_deployment_unused_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openstackcredentials',
            name='identity_api_version',
        ),
        migrations.AddField(
            model_name='openstack',
            name='identity_api_version',
            field=models.CharField(blank=True, choices=[('v2.0', 'v2.0'), ('v3.0', 'v3.0')], max_length=10, null=True),
        ),
    ]
