# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baselaunch', '0012_move_openstackcredentials_identity_api_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('app_config', models.TextField(blank=True, max_length=16384, null=True)),
                ('app_deployment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_version_cloud_config', to='baselaunch.ApplicationDeployment')),
                ('app_version_cloud_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_version_cloud_config', to='baselaunch.ApplicationVersionCloudConfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usage',
                'ordering': ['added'],
            },
        )
    ]
