# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0014_add_cloud_default_app_and_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationversion',
            unique_together=set([('application', 'version')]),
        ),
    ]
