# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0016_add_more_task_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='access_instructions_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
