# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0017_cloud_access_instructions_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cloud',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='application',
            name='maintainer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='summary',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='backend_component_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='frontend_component_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='frontend_component_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
