
# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 18:16
from __future__ import unicode_literals

import django
import fernet_fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0018_auto_20170613_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='AZURE',
            fields=[
                ('cloud_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='baselaunch.Cloud')),
                ('region_name', models.CharField(max_length=100)),
                ('resource_group', models.CharField(max_length=100)),
                ('storage_account', models.CharField(max_length=100)),
                ('vm_default_user_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Azure',
                'verbose_name_plural': 'Azure',
            },
            bases=('baselaunch.cloud',),
        ),
        migrations.CreateModel(
            name='AzureCredentials',
            fields=[
                ('credentials_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='baselaunch.Credentials')),
                ('subscription_id', models.CharField(max_length=50)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('secret', fernet_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True)),
                ('tenant', models.CharField(blank=True, max_length=50, null=True))
            ],
            options={
                'verbose_name': 'Azure Credentials',
                'verbose_name_plural': 'Azure Credentials',
            },
            bases=('baselaunch.credentials',),
        )
    ]