# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0018_auto_20170613_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCE',
            fields=[
                ('cloud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baselaunch.Cloud')),
                ('region_name', models.CharField(max_length=100)),
                ('zone_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'GCE',
                'verbose_name_plural': 'GCE',
            },
            bases=('baselaunch.cloud',),
        ),
        migrations.CreateModel(
            name='GCECredentials',
            fields=[
                ('credentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baselaunch.Credentials')),
                ('credentials', fernet_fields.fields.EncryptedTextField()),
            ],
            options={
                'verbose_name': 'GCE Credentials',
                'verbose_name_plural': 'GCE Credentials',
            },
            bases=('baselaunch.credentials',),
        ),
    ]
