
# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 18:16
from __future__ import unicode_literals

import django
import fernet_fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0019_azure_credentials'),
    ]

    operations = [
        migrations.DeleteModel('AZURE'),
        migrations.CreateModel(
            name='Azure',
            fields=[
                ('cloud_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='baselaunch.Cloud')),
                ('region_name', models.CharField(max_length=100)),
                ('resource_group', models.CharField(max_length=100)),
                ('storage_account', models.CharField(max_length=100)),
                ('vm_default_user_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Azure',
                'verbose_name_plural': 'Azure',
            },
            bases=('baselaunch.cloud',),
        )
    ]