# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0020_azure_model_change'),
        ('baselaunch', '0019_gce_gcecredentials'),
    ]

    operations = [
    ]
