# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0023_auto_20170912_1639'),
        ('djcloudbridge', '0001_initial'),
    ]
    
    DROP_DJCLOUDBRIDGE_TABLES = """\
        DROP TABLE IF EXISTS djcloudbridge_Cloud;
        DROP TABLE IF EXISTS djcloudbridge_AWS;
        DROP TABLE IF EXISTS djcloudbridge_EC2;
        DROP TABLE IF EXISTS djcloudbridge_S3;
        DROP TABLE IF EXISTS djcloudbridge_OpenStack;
        DROP TABLE IF EXISTS djcloudbridge_Azure;
        DROP TABLE IF EXISTS djcloudbridge_GCE;
        DROP TABLE IF EXISTS djcloudbridge_Credentials;
        DROP TABLE IF EXISTS djcloudbridge_AWSCredentials;
        DROP TABLE IF EXISTS djcloudbridge_OpenStackCredentials;
        DROP TABLE IF EXISTS djcloudbridge_AzureCredentials;
        DROP TABLE IF EXISTS djcloudbridge_GCECredentials;
        DROP TABLE IF EXISTS djcloudbridge_UserProfile;
    """

    database_operations = [
        migrations.RunSQL(DROP_DJCLOUDBRIDGE_TABLES),
        migrations.AlterModelTable('Cloud', 'djcloudbridge_Cloud'),
        migrations.AlterModelTable('AWS', 'djcloudbridge_AWS'),
        migrations.AlterModelTable('EC2', 'djcloudbridge_EC2'),
        migrations.AlterModelTable('S3', 'djcloudbridge_S3'),
        migrations.AlterModelTable('OpenStack', 'djcloudbridge_OpenStack'),
        migrations.AlterModelTable('Azure', 'djcloudbridge_Azure'),
        migrations.AlterModelTable('GCE', 'djcloudbridge_GCE'),
        migrations.AlterModelTable('Credentials', 'djcloudbridge_Credentials'),
        migrations.AlterModelTable('AWSCredentials', 'djcloudbridge_AWSCredentials'),
        migrations.AlterModelTable('OpenStackCredentials', 'djcloudbridge_OpenStackCredentials'),
        migrations.AlterModelTable('AzureCredentials', 'djcloudbridge_AzureCredentials'),
        migrations.AlterModelTable('GCECredentials', 'djcloudbridge_GCECredentials'),
        migrations.AlterModelTable('UserProfile', 'djcloudbridge_UserProfile'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='aws',
            name='cloud_ptr',
        ),
        migrations.RemoveField(
            model_name='aws',
            name='compute',
        ),
        migrations.RemoveField(
            model_name='aws',
            name='object_store',
        ),
        migrations.RemoveField(
            model_name='awscredentials',
            name='credentials_ptr',
        ),
        migrations.RemoveField(
            model_name='azure',
            name='cloud_ptr',
        ),
        migrations.RemoveField(
            model_name='azurecredentials',
            name='credentials_ptr',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='cloud',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='gce',
            name='cloud_ptr',
        ),
        migrations.RemoveField(
            model_name='gcecredentials',
            name='credentials_ptr',
        ),
        migrations.RemoveField(
            model_name='openstack',
            name='cloud_ptr',
        ),
        migrations.RemoveField(
            model_name='openstackcredentials',
            name='credentials_ptr',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='applicationdeploymenttask',
            name='result',
        ),
        migrations.RemoveField(
            model_name='applicationdeploymenttask',
            name='status',
        ),
        migrations.DeleteModel(
            name='AWS',
        ),
        migrations.DeleteModel(
            name='AWSCredentials',
        ),
        migrations.DeleteModel(
            name='Azure',
        ),
        migrations.DeleteModel(
            name='AzureCredentials',
        ),
        migrations.DeleteModel(
            name='Cloud',
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
        migrations.DeleteModel(
            name='EC2',
        ),
        migrations.DeleteModel(
            name='GCE',
        ),
        migrations.DeleteModel(
            name='GCECredentials',
        ),
        migrations.DeleteModel(
            name='OpenStack',
        ),
        migrations.DeleteModel(
            name='OpenStackCredentials',
        ),
        migrations.DeleteModel(
            name='S3',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]

    operations =[
        migrations.AlterField(
            model_name='applicationdeployment',
            name='target_cloud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcloudbridge.Cloud'),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='default_cloud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djcloudbridge.Cloud'),
        ),
        migrations.AlterField(
            model_name='applicationversioncloudconfig',
            name='cloud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_version_config', to='djcloudbridge.Cloud'),
        ),
        migrations.AlterField(
            model_name='cloudimage',
            name='cloud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djcloudbridge.Cloud'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations),
        migrations.AddField(
            model_name='applicationdeploymenttask',
            name='_result',
            field=models.TextField(blank=True, db_column='result', help_text='Result of Celery task', max_length=16384, null=True),
        ),
        migrations.AddField(
            model_name='applicationdeploymenttask',
            name='_status',
            field=models.CharField(blank=True, db_column='status', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdeploymenttask',
            name='action',
            field=models.CharField(blank=True, choices=[('LAUNCH', 'Launch'), ('HEALTH_CHECK', 'Health check'), ('RESTART', 'Restart'), ('DELETE', 'Delete')], max_length=255, null=True),
        ),
    ]