# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0024_refactor_to_djcloudbridge'),
        ('public_appliances', '0001_initial'),
    ]

    DROP_PUBLIC_APPLIANCE_TABLES = """\
        DROP TABLE IF EXISTS public_appliances_Location;
        DROP TABLE IF EXISTS public_appliances_PublicService;
        DROP TABLE IF EXISTS public_appliances_PublicService_sponsors;
        DROP TABLE IF EXISTS public_appliances_Sponsor;
        DROP TABLE IF EXISTS public_appliances_PublicService_Tags;
        DROP TABLE IF EXISTS public_appliances_Tag;
    """

    database_operations = [
        migrations.RunSQL(DROP_PUBLIC_APPLIANCE_TABLES),
        migrations.AlterModelTable('Location', 'public_appliances_Location'),
        migrations.AlterModelTable('PublicService', 'public_appliances_PublicService'),
        migrations.AlterModelTable('Sponsor', 'public_appliances_Sponsor'),
        migrations.AlterModelTable('Tag', 'public_appliances_Tag')
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='publicservice',
            name='application',
        ),
        migrations.RemoveField(
            model_name='publicservice',
            name='location',
        ),
        migrations.RemoveField(
            model_name='publicservice',
            name='sponsors',
        ),
        migrations.RemoveField(
            model_name='publicservice',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PublicService',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.DeleteModel(
            name='Tag',
        )
    ]

    operations =[
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations),
    ]