# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselaunch', '0025_refactor_to_public_appliances'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdeployment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
