# Generated by Django 2.2.9 on 2020-01-24 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('djcloudbridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('FEATURED', 'Featured'), ('GALAXY', 'Galaxy'), ('SCALABLE', 'Scalable'), ('VM', 'Virtual machine')], max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'App categories',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('DEV', 'Development'), ('CERTIFICATION', 'Certification'), ('LIVE', 'Live')], default='DEV', max_length=50, null=True)),
                ('summary', models.CharField(blank=True, max_length=140, null=True)),
                ('maintainer', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=32767, null=True)),
                ('info_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('icon_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('default_launch_config', models.TextField(blank=True, help_text='Application-wide initial configuration data to parameterize the launch with.', max_length=1048576, null=True)),
                ('display_order', models.IntegerField(default='10000')),
                ('category', models.ManyToManyField(blank=True, to='cloudlaunch.AppCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('archived', models.BooleanField(blank=True, default=False)),
                ('application_config', models.TextField(blank=True, help_text='Application configuration data used for this launch.', max_length=16384, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30)),
                ('frontend_component_path', models.CharField(blank=True, max_length=255, null=True)),
                ('frontend_component_name', models.CharField(blank=True, max_length=255, null=True)),
                ('backend_component_name', models.CharField(blank=True, max_length=255, null=True)),
                ('default_launch_config', models.TextField(blank=True, help_text='Version specific configuration data to parameterize the launch with.', max_length=1048576, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cloudlaunch.Application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationVersionTargetConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_launch_config', models.TextField(blank=True, help_text='Target specific initial configuration data to parameterize the launch with.', max_length=16384, null=True)),
                ('application_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_version_config', to='cloudlaunch.ApplicationVersion')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_cloudlaunch.applicationversiontargetconfig_set+', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_cloudlaunch.deploymenttarget_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Deployment Target',
                'verbose_name_plural': 'Deployment Targets',
            },
        ),
        migrations.CreateModel(
            name='HostDeploymentTarget',
            fields=[
                ('deploymenttarget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cloudlaunch.DeploymentTarget')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
            },
            bases=('cloudlaunch.deploymenttarget',),
        ),
        migrations.CreateModel(
            name='KubernetesDeploymentTarget',
            fields=[
                ('deploymenttarget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cloudlaunch.DeploymentTarget')),
                ('kube_config', models.CharField(max_length=16384)),
            ],
            options={
                'verbose_name': 'Kubernetes Cluster',
                'verbose_name_plural': 'Kubernetes Clusters',
            },
            bases=('cloudlaunch.deploymenttarget',),
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('app_config', models.TextField(blank=True, max_length=16384, null=True)),
                ('app_deployment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cloudlaunch.ApplicationDeployment')),
                ('app_version_target_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cloudlaunch.ApplicationVersionTargetConfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usage',
                'ordering': ['added'],
            },
        ),
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('public_key', models.TextField(max_length=16384)),
                ('default', models.BooleanField(blank=True, default=False, help_text='If set, use as the default public key')),
                ('fingerprint', models.CharField(blank=True, max_length=100, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_key', to='djcloudbridge.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('image_id', models.CharField(max_length=50, verbose_name='Image ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcloudbridge.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='applicationversiontargetconfig',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_version_config', to='cloudlaunch.DeploymentTarget'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='default_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cloudlaunch.DeploymentTarget'),
        ),
        migrations.CreateModel(
            name='ApplicationDeploymentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('celery_id', models.TextField(blank=True, help_text='Celery task id for any background jobs running on this deployment', max_length=64, null=True, unique=True)),
                ('action', models.CharField(blank=True, choices=[('LAUNCH', 'Launch'), ('HEALTH_CHECK', 'Health check'), ('RESTART', 'Restart'), ('DELETE', 'Delete')], max_length=255, null=True)),
                ('_result', models.TextField(blank=True, db_column='result', help_text='Result of Celery task', max_length=16384, null=True)),
                ('_status', models.CharField(blank=True, db_column='status', max_length=64, null=True)),
                ('traceback', models.TextField(blank=True, help_text='Celery task traceback, if any', max_length=16384, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cloudlaunch.ApplicationDeployment')),
            ],
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='application_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudlaunch.ApplicationVersion'),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='credentials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_creds', to='djcloudbridge.Credentials'),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='deployment_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudlaunch.DeploymentTarget'),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='default_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cloudlaunch.ApplicationVersion'),
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('key', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Key')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='applicationversiontargetconfig',
            unique_together={('application_version', 'target')},
        ),
        migrations.CreateModel(
            name='ApplicationVersionCloudConfig',
            fields=[
                ('applicationversiontargetconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cloudlaunch.ApplicationVersionTargetConfig')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudlaunch.Image')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('cloudlaunch.applicationversiontargetconfig',),
        ),
        migrations.AlterUniqueTogether(
            name='applicationversion',
            unique_together={('application', 'version')},
        ),
        migrations.CreateModel(
            name='CloudDeploymentTarget',
            fields=[
                ('deploymenttarget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cloudlaunch.DeploymentTarget')),
                ('target_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcloudbridge.Zone')),
            ],
            options={
                'verbose_name': 'Cloud',
                'verbose_name_plural': 'Clouds',
                'unique_together': {('deploymenttarget_ptr', 'target_zone')},
            },
            bases=('cloudlaunch.deploymenttarget',),
        ),
    ]
