# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudlaunch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='display_order',
            field=models.IntegerField(default='10000'),
        ),
    ]
