# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudlaunch', '0002_application_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='credentials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_creds', to='djcloudbridge.Credentials'),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ManyToManyField(blank=True, to='cloudlaunch.AppCategory'),
        ),
    ]
