# Generated by Django 2.1.2 on 2018-10-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudlaunch', '0006_add_multiple_api_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='applicationdeployment',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='default',
            field=models.BooleanField(blank=True, default=False, help_text='If set, use as the default public key'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
